/* Auto-generated by AutoZig - Do not edit */
/* eslint-disable */

export interface WasmExports {
  add(a: number, b: number): number;
  multiply(a: number, b: number): number;
  get_version(): number;
  square(x: number): number;
  is_even(n: number): boolean;
}

export interface AutoZigWasm {
  exports: WasmExports;
  memory: WebAssembly.Memory;
  instance: WebAssembly.Instance;
}

/** Load WASM module from URL */
export function loadWasm(path: string): Promise<AutoZigWasm>;

/** Load WASM module from ArrayBuffer */
export function loadWasmSync(buffer: ArrayBuffer): Promise<AutoZigWasm>;
